version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod +x get_helm.sh && ./get_helm.sh
      - yum install -y jq
  pre_build:
    commands:
      - aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_DEFAULT_REGION"
      - ORDER_IMAGE=$(jq -r '.["order-service"]' $CODEBUILD_SRC_DIR_BuildOutput/images.json)
      - WORKER_IMAGE=$(jq -r '.["worker-service"]' $CODEBUILD_SRC_DIR_BuildOutput/images.json)
      - FRONTEND_IMAGE=$(jq -r '.["frontend"]' $CODEBUILD_SRC_DIR_BuildOutput/images.json)
  build:
    commands:
      - "helm upgrade --install order-service helm/order-service --namespace default --set image.repository=$(echo $ORDER_IMAGE | cut -d: -f1) --set image.tag=$(echo $ORDER_IMAGE | cut -d: -f2)"
      - "helm upgrade --install worker-service helm/worker-service --namespace default --set image.repository=$(echo $WORKER_IMAGE | cut -d: -f1) --set image.tag=$(echo $WORKER_IMAGE | cut -d: -f2)"
      - "helm upgrade --install frontend helm/frontend --namespace default --set image.repository=$(echo $FRONTEND_IMAGE | cut -d: -f1) --set image.tag=$(echo $FRONTEND_IMAGE | cut -d: -f2)"
